spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      username: ${CONFIG_SERVICE_USERNAME}
      password: ${CONFIG_SERVICE_PASS}
server:
  port: 8091


